name: Build

on: push

jobs:
  build:
    name: 'G=${{ matrix.gradle }} | J=${{ matrix.java }} | AGP=${{ matrix.agp }} | K=${{ matrix.kotlin }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle: [7.6, 8.1.1]
        java: [11, 17]
        agp: [7.4.2, 8.0.1]
        kotlin: [1.6.21, 1.7.21, 1.8.21]
        exclude:
          # AGP 8.0+ requires Gradle 8.0
          - agp: 8.0.1
            gradle: 7.6
          # AGP 8.0+ requires JDK 17
          - agp: 8.0.1
          - java: 11

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: :app:assembleDebug -PagpVersion=${{ matrix.agp }} -PkotlinVersion=${{ matrix.kotlin }} --scan
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: G-${{ matrix.gradle }}-J-${{ matrix.java }}-AGP-${{ matrix.agp }}-K-${{ matrix.kotlin }}
          path: app/build/outputs/apk/debug/app-debug.apk
