name: Build

on: push

jobs:
  build:
    name: 'G=${{ matrix.gradle }} | J=${{ matrix.java }} | AGP=${{ matrix.agp }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle: [6.9, 7.4.2]
        java: [ 1.8, 11 ]
        agp: [ 4.0.2, 4.1.3, 4.2.2, 7.0.2, 7.1.3, 7.2.1, 7.3.0-beta04 ]
        exclude:
          # AGP 7.0.0+ requires JDK 11
          - agp: 7.0.2
            java: 1.8
          - agp: 7.1.3
            java: 1.8
          - agp: 7.2.1
            java: 1.8
          - agp: 7.3.0-beta04
            java: 1.8
          # AGP 7.0.0+ requires Gradle 7.0.2+
          - agp: 7.0.2
            gradle: 6.9
          - agp: 7.1.3
            gradle: 6.9
          # AGP 7.2.0+ requires Gradle 7.3.3+
          - agp: 7.2.1
            gradle: 6.9
          - agp: 7.3.0-beta04
            gradle: 6.9
          # AGP below 4.1 is incompatible with Gradle 7.0.0
          - agp: 4.0.2
            gradle: 7.4.2

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: :app:assembleDebug -PagpVersion=${{ matrix.agp }} --scan
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: G-${{ matrix.gradle }}-J-${{ matrix.java }}-AGP-${{ matrix.agp }}
          path: app/build/outputs/apk/debug/app-debug.apk
